import assert from "node:assert/strict";
import test from "node:test";

test("renders the canonical-source control plane", async () => {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);
  const response = await worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
  const html = await response.text();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);
  assert.match(html, /YouTube AI Factory V2/i);
  assert.match(html, /Single source of truth policy active/i);
  assert.match(html, /Production remains locked/i);
  assert.match(html, /25 evidence-ready · 29 implemented \/ 33/i);
  assert.match(html, /Lease &amp; Fencing/i);
  assert.match(html, /Definition of Ready Resolver/i);
  assert.match(html, /Standard &amp; Policy Registry/i);
  assert.match(html, /Evidence Store/i);
  assert.match(html, /Provider Adapter Framework/i);
  assert.match(html, /Cost Reservation &amp; Ledger/i);
  assert.match(html, /Two-phase reservation/i);
  assert.match(html, /Capability Registry &amp; Dispatch Guard/i);
  assert.match(html, /nine-step fail-closed guard/i);
  assert.match(html, /Stage Runner Framework/i);
  assert.match(html, /deterministic preflight/i);
  assert.match(html, /Tournament Engine/i);
  assert.match(html, /deterministic seeded selection/i);
  assert.match(html, /Media Worker Runtime/i);
  assert.match(html, /Pinned CPU-only image/i);
  assert.match(html, /Cost Benchmark/i);
  assert.match(html, /selected PROFILE=REDUCED/i);
  assert.match(html, /Deterministic Measurement/i);
  assert.match(html, /All 15 MSR-01 measurements/i);
  assert.match(html, /Gold Set &amp; Calibration/i);
  assert.match(html, /15 real rejected masters/i);
  assert.match(html, /Aligner Calibration/i);
  assert.match(html, /10–15 real human-reader samples/i);
  assert.match(html, /Truth Layer/i);
  assert.match(html, /Intelligence &amp; Anti-copy/i);
  assert.match(html, /ShotCueProgram Compiler/i);
  assert.match(html, /no fixed shot-count gate/i);
  assert.match(html, /Media Layer/i);
  assert.match(html, /pre-byte rights eligibility/i);
  assert.match(html, /Assurance Panel/i);
  assert.match(html, /HARD_GATE waits for 36 human anchors/i);
  assert.match(html, /Publishing/i);
  assert.match(html, /keeps auto-publish OFF/i);
  assert.match(html, /Human Evidence/i);
  assert.match(html, /explicit real-human allowlist identity/i);
  assert.match(html, /Policy Defense · Minimum/i);
  assert.match(html, /Evolution pipeline implemented/i);
  assert.match(html, /Observability &amp; Operator UI/i);
  assert.match(html, /Trace reconstruction now proves the complete provider, cost and output chain/i);
  assert.match(html, /G11–G15 Enforcement/i);
  assert.match(html, /Sealed threshold diffs, OPERATE protected paths, shadow-gated meta-change, append-only gold retirement and PC1–PC8 publishing checks/i);
  assert.match(html, /Evolution Pipeline/i);
  assert.match(html, /Structural strictness audit, qualification shadow replay, five-part evidence bundles, exact owner-command promotion binding and one-key rollback/i);
  assert.match(html, /FAIL · measured failure/i);
  assert.match(html, /NOT_EVALUATED · not measured/i);
  assert.match(html, /QUALIFICATION FIXTURE — NOT A RELEASE CANDIDATE/i);
  assert.match(html, /Unified human-touchpoint queue/i);
  assert.match(html, /D1–D5 side-by-side desk \+ diff/i);
  assert.match(html, /Structured rejection labeling/i);
  assert.match(html, /Generate Evidence Report action/i);
  assert.match(html, /Attention budget clock/i);
  assert.match(html, /trace_id[\s\S]*provider request\/response, settled cost and sealed output/i);
  assert.match(html, /WP-16, WP-17, WP-20, WP-21, WP-23, WP-24, WP-25, WP-26, WP-27 and minimum WP-29 are evidence-ready/i);
  assert.match(html, /WP-22 remains warning-only pending anchors, gold evidence and critic qualification/i);
  assert.match(html, /WP-24 activation awaits 14–28 day production Analytics and an owner-issued promotion command/i);
  assert.match(html, /WP-27 activation requires a real qualification shadow run, stored evidence bundle and exact owner-signed PROMOTE_EVOLUTION command/i);
  assert.match(html, /YouTube transport and production provider dispatch remain locked/i);
  assert.match(html, /Provider dispatch[\s\S]*OFF/i);
  assert.match(html, /Production spend[\s\S]*\$0/i);
  assert.match(html, /Automatic publishing[\s\S]*BLOCKED/i);
  assert.doesNotMatch(html, /codex-preview/i);
});
